# This is a basic workflow to help you get started with Actions

name: tag push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '2023.1?[0-9].[1-3]?[0-9]'
    # branches:
      # - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  matrix:
    name: The Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        inputs: ${{ fromJson('[]') }}
    steps:
      - uses: actions/checkout@v3
      - name: print shit
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          prev_tag=$(gh release list -L 2 --json tagName -q '.[1].tagName')
          echo "Previous tag: ${prev_tag}"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: [matrix]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: print shit
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "ref: ${{ github.ref }}"

