# This is a basic workflow to help you get started with Actions

name: tag push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '2023.1?[0-9].[1-3]?[0-9]'
    # branches:
      # - 'main'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  get_previous_tag:
    name: Get previous tag
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.get_previous_tag.outputs.prev_tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Get previous tag
        id: get_previous_tag
        # https://cli.github.com/manual/gh_release_list
        # -L 2: get the last 2 releases
        # --json tagName: get the tag name
        # -q '.[1].tagName': get the second release's tag name
        run: |
          prev_tag=$(gh release list -L 2 --json tagName -q '.[1].tagName')
          echo "Previous tag: ${prev_tag}"
          echo "prev_tag=${prev_tag}" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ github.token }}
  check_diff:
    needs: [get_previous_tag]
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        with:
          filters: |
            foo: '.github/workflows/tag-push.yml'
          base: ${{ needs.get_previous_tag.outputs.value }}
  build:
    # The type of runner that the job will run on
    needs: [get_previous_tag]
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: print shit
        run: |
          echo "ref_name: ${{ github.ref_name }}"
          echo "ref_type: ${{ github.ref_type }}"
          echo "ref: ${{ github.ref }}"
          echo "needs.get_previous_tag.outputs.value: ${{ needs.get_previous_tag.outputs.value }}"

